version: '3.8'
services:
  front-end:
    build: ./frontend/
    ports:
      - 5000:5000 
  back-end:
    build: ./backend/
    ports:
      - 8080:8080
    depends_on:
      - data-base
    environment:
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=data-base
      - POSTGRES_USER=the_user
      - POSTGRES_PASSWORD=really_simple_password
      - POSTGRES_DATABASE=container_exercises
  redis-cache:
    image: redis:6.2-alpine

  data-base:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=the_user
      - POSTGRES_PASSWORD=really_simple_password
      - POSTGRES_DB=container_exercises
    container_name: postgres_db